<?php

/**
 * Created by PhpStorm.
 * User: GORILLA
 * Date: 22/10/2017
 * Time: 22:14
 */
class ServicoModel extends Model
{
    protected $table = 'servico';

    public function salvar($data){

        if(array_key_exists('id_servico',$data)){
            $id['id_servico'] = $data['id_servico'];
            return $this->update($data,$id);
        }else{
            return $this->inserir($data);
        }
    }

    public function All(){
        return parent::buscarAllModel($this->table);
    }
    public function exclui($post)
    {
        return parent::excluirModel($this->table, $post); // TODO: Change the autogenerated stub
    }

    private function inserir($data){
        return parent::gravarModel($this->table,$data);
    }

    private function update($data,$id){

        return parent::alterarModel($this->table,$data,$id);
    }
    public function filtrar($post)
    {
        return parent::filtrar($this->table, $post); // TODO: Change the autogenerated stub
    }

    public function getById($id){
        return parent::buscarModel($this->table,$id);
    }
    public function getNomeServicoById($id){
        $result = parent::where($this->table,$id,'nm_servico');
        return $result['nm_servico'];
    }
    public function getServicos()
    {
      return parent::buscarColumsModel($this->table,['id_servico'=>'id_servico','nm_servico' =>'nm_servico']) ;
    }
}