<?php

/**
 * Created by PhpStorm.
 * User: GORILLA
 * Date: 12/11/2017
 * Time: 16:22
 */
class UsuarioAgendaModel extends Model
{
    protected $table ='usuario_agenda';

    public function All(){
        return $this->buscarAllModel($this->table);
    }
    public function salvar($data){

        if(array_key_exists('id_usuario_agenda',$data)){
            $id['id_usuario_agenda'] = $data['id_usuario_agenda'];
            return $this->update($data,$id);
        }else{
            return $this->inserir($data);
        }
    }

    public function exclui($post)
    {
        return parent::excluirModel($this->table, $post); // TODO: Change the autogenerated stub
    }

    private function inserir($data){
        return parent::gravarModel($this->table,$data);
    }

    private function update($data,$id){

        return parent::alterarModel($this->table,$data,$id);
    }
    public function filtrar($post)
    {
        return parent::filtrar($this->table, $post); // TODO: Change the autogenerated stub
    }

    public function getById($id){

        return parent::buscarModel($this->table,$id);
    }
}