<?php

/**
 * Created by PhpStorm.
 * User: GORILLA
 * Date: 24/10/2017
 * Time: 01:28
 */
class RacaModel extends Model
{
    protected $table = 'raca';

    public function salvar($data){

        if(array_key_exists('id_raca',$data)){
            $id['id_raca'] = $data['id_raca'];
            return $this->update($data,$id);
        }else{
            return $this->inserir($data);
        }
    }

    public function All(){
        return parent::buscarAllModel($this->table);
    }
    public function exclui($post)
    {
        return parent::excluirModel($this->table, $post); // TODO: Change the autogenerated stub
    }

    private function inserir($data){
        return parent::gravarModel($this->table,$data);
    }

    private function update($data,$id){

        return parent::alterarModel($this->table,$data,$id);
    }
    public function filtrar($post)
    {
        return parent::filtrar($this->table, $post); // TODO: Change the autogenerated stub
    }

    public function getNomeRacaById($post,$return){
        $result= parent::where($this->table,$post,$return);
        return $result['nm_raca'];
    }
    public function getNomeEspecieByRacaId($post,$return){
        $result = parent::where($this->table,$post,'id_especie');
        /**@var $esp EspecieModel*/
        $esp = fabric('EspecieModel');

        $result = $esp->getNomeEspecieById(['id_especie'=>$result['id_especie']],'nm_especie');
        #xd($result);
        return $result['nm_especie'];
    }
    public function get_racas($term){
        return parent::buscarModel($this->table,$term);
    }
    public function where($post,$return){
       return parent::where($this->table,$post,$return);
    }
    public function getById($id){
        return parent::buscarModel($this->table,$id);
    }
}